baseURL      = "http://banditbenchmark.com"
languageCode = "en-us"
title        = "Bandit Benchmarking"

#this removes the default tag and category taxonomies
taxonomies = []

#this prevents these kinds of pages from being rendered
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[deployment]
    order = [".jpg$", ".gif$"] # causes these files to upload first

    [[deployment.targets]]
        name = "default"
        URL = "azblob://$web"
        # include = "**.html" # would only include files with ".html" suffix
        # exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix

    [[deployment.matchers]]
        pattern = "^.+\\.(js|css|svg|ttf)$"
        cacheControl = "max-age=31536000, no-transform, public"
        gzip = true

    [[deployment.matchers]]
        pattern = "^.+\\.(png|jpg)$"
        cacheControl = "max-age=31536000, no-transform, public"
        gzip = false

    [[deployment.matchers]]
        pattern = "^.+\\.(html|xml|json)$"
        gzip = true       
